dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: HMkTPeYP0+IqqqdeHA4Bkw2RrkoD5YGEogfzagxXu8fzR7GUuNhF3M7Qx7TcxnVYRelC0nwozqwKP8GsqiE2FDE6gIorEfrcN6/X4fv9FF0bVrXQ1woc0RptAU6ELvFW7CxknyA5SWtvhO2lDrRC3OGPqObU4eyzjxAVNjXdCjO8YKx55spBBQolC9bvmFHjqtsaMmx2sxMLb+5CVHCppe32O+1OOOX/W6MGDHLVk7HnDXqepwQZPXj2U41uxaZkPxKzd6r2wAwXKL8c2eBJONzYLIfhyBXYwthExEE5qhp+xifGrd2ItNUx2Myq6LXqh/+C497FUUR+qg3JAqILJqvU3Jec/OZrucejQE5dCN5a2cdl5NXTae7F0fBrjdb/GqB68xM7WFx4XS3zey91Y161ZLxmOvJ54+rd3UvkXjYeJMTeI9HxlTim0KZjFQS7U8gflfyEYWyLl2wFzvFwQ2KVq7fFhpAYCEbBgiTRPKzuFbrlA0yw5SR7tgBtQCFMAsZwfNbczq1Wt3jnJt/hA4SnJBZ8505XPwE7pamXEh7GIk81Yedi9khGVclkJziHUW+5EaNDNSsHcEBURWV9psM6XKC/bQcj6BRZKShnmJ6ri35+YhcQ5pFAfLACRtO39AT3YBWeypOS1Upb3TAmoFnd4N+0xayNAtcrb4tfaIk=
