dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: VKW3IfV6wbJCCNZISwInR3YtPMSxaoZjsnny26KD86Ft14CzsDdaYijMogh3xG839T+QkB+GPsJ3KZbqrvOMuq5j/O1Kru+c/H6/0lioTCzeImoX3Sfzsnx6DE49I5nq+WCKBomPDjrITHxPlzUdnTK8fyUWDvdFgOj7F/pGKoQvrMJn+OcPoh2jnJDg+qpLIlswzV91zkI7yphZg372B0720mhpaiS6TjKLW1/iVQSqkOEynQcE7aH++sT8tFskpch454zURpx60iUCO7OR/Dc+EccLH4T5QT+ntHxxUXiMGmeIspYyqqbet2XkU/+v1huchL6ai2bw5bToCiHAh4MFNBu1BN8V/FwyT0Nj+Wd+dQanVFR4YTtPGHWhshq/j/6OqVRV+f5ly/eO2ZsoI9iXAuo8dbQKsWKg0ihdDMJnMpm8melC8ENQwT2s1qmEK0MVLS6JzogLfq7lc599zdyrT3WZLKtIYqDzMkjEUoPIk0D16K72/83bcT9X7uvyW2PFCP2OUP3Y0j17D2yig0g9tHoyLAHszjutAbIZPuvxYcfL2klkMx020rLF2iiabwQPdQsOgb4vxE1U7fAZV/VfnKo+e4Q7kXnF/kBDBRbIVicEMUzPwwNyDbHA7MYGugqBuKmOJWy7/zDziM1rL1ZYyMd4Lpef/OhEDZGia6c=
